/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view;

import ihm.PanelHistorique;
import ihm.PanelProchainCoup;
import ihm.PanelSynthese;
import java.util.Observable;
import java.util.Observer;
import model.Partie;

/**
 *
 * @author zouhairhajji
 */
public class View extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form View
     */
    public View(Partie partie) {
        this.partie = partie;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProchainCoup = new PanelProchainCoup();
        panelSynthese = new PanelSynthese(this.partie);
        panelHistorique = new PanelHistorique(this.partie);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelProchainCoup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSynthese, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(panelProchainCoup, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSynthese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    /*
    public void chargerList(){
        this.defaultModel.setRowCount(0);
        for(int i = 0; i < partie.getNbrCoups();i++){
            this.defaultModel.addRow(new String[]{""+i,partie.getChoix(0, i),partie.getChoix(1, i),partie.getScore(0, i)+"",partie.getScore(1, i)+""});
        }
        this.nbCoup.setText(this.partie.getNbrCoups()+"");
        this.scoreA.setText(this.partie.getScorePlayer(0)+"");
        this.scoreB.setText(this.partie.getScorePlayer(1)+"");
    }
    
    
    private void initInterface(){
        defaultModel = new DefaultTableModel( new String[]{"N°","Choix A", "Choix B", "Gain A", "Gain B "}, 0 ) ;
        this.jTable1.setModel(defaultModel);
    }
    
    */

    public PanelHistorique getPanelHistorique() {
        return panelHistorique;
    }

    public PanelSynthese getPanelSynthese() {
        return panelSynthese;
    }

    public PanelProchainCoup getPanelProchainCoup() {
        return panelProchainCoup;
    }
    
    
    
    
    private Partie partie;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ihm.PanelHistorique panelHistorique;
    private ihm.PanelProchainCoup panelProchainCoup;
    private ihm.PanelSynthese panelSynthese;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (o instanceof Partie) {
            this.panelHistorique.chargerList();
            this.panelSynthese.chargerInformation();
        }
    }


    
   
}
