/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.awt.LayoutManager;
import javax.swing.table.DefaultTableModel;
import model.Partie;

/**
 *
 * @author zouhairhajji
 */
public class PanelHistorique extends javax.swing.JPanel {

    /**
     * Creates new form PanelHistorique
     */
    public PanelHistorique() {
        this(new Partie());
    }

    public PanelHistorique(Partie partie) {
        this.partie = partie;
        initComponents();
        initInterface();
    }
    private void initInterface(){
        tableModel = new DefaultTableModel( new String[]{"N°","Choix A", "Choix B", "Gain A", "Gain B "}, 0 ) ;
        this.tableHistorique.setModel(tableModel);
    }
    
    public void chargerList(){
        this.tableModel.setRowCount(0);
        for(int i = 0; i < partie.getNbrCoups();i++){
            this.tableModel.addRow(new String[]{""+i,partie.getChoix(0, i),partie.getChoix(1, i),partie.getScore(0, i)+"",partie.getScore(1, i)+""});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableHistorique = new javax.swing.JTable();

        tableHistorique.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableHistorique);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public DefaultTableModel getTableModel() {
        return tableModel;
    }

    private DefaultTableModel tableModel;
    private Partie partie;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableHistorique;
    // End of variables declaration//GEN-END:variables
}
